project:
  type: website
  output-dir: docs

website:
  title: "Paola Arguello"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: projects/genomics-to-insight.qmd
        text: Clinical Genomics Workflow
      - href: about.qmd
        text: About
    right:
      - icon: github
        href: https://github.com/YOURUSERNAME

format:
  html:
    theme: cosmo
    toc: true